// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using VirtualTryonWomenFashion.Data.Models;

namespace VirtualTryonWomenFashion.Data.DBContext;

public partial class VirtualTryonWomenFashionContext : DbContext
{
    public VirtualTryonWomenFashionContext()
    {
    }

    public VirtualTryonWomenFashionContext(DbContextOptions<VirtualTryonWomenFashionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Aiconversation> Aiconversations { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<CategorySizeTemplate> CategorySizeTemplates { get; set; }

    public virtual DbSet<Characteristic> Characteristics { get; set; }

    public virtual DbSet<Color> Colors { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<OccasionPreference> OccasionPreferences { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<OrderRefund> OrderRefunds { get; set; }

    public virtual DbSet<OrderRefundDetail> OrderRefundDetails { get; set; }

    public virtual DbSet<OrderRefundImage> OrderRefundImages { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductColor> ProductColors { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductInSaleCampaign> ProductInSaleCampaigns { get; set; }

    public virtual DbSet<ProductVariant> ProductVariants { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SaleCampaign> SaleCampaigns { get; set; }

    public virtual DbSet<Size> Sizes { get; set; }

    public virtual DbSet<SkinTone> SkinTones { get; set; }

    public virtual DbSet<StatusLog> StatusLogs { get; set; }

    public virtual DbSet<StyleType> StyleTypes { get; set; }

    public virtual DbSet<SuggestedOutfit> SuggestedOutfits { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<TicketChat> TicketChats { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<TryOnSlot> TryOnSlots { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserInteraction> UserInteractions { get; set; }

    public virtual DbSet<Wallet> Wallets { get; set; }

    public virtual DbSet<Wishlist> Wishlists { get; set; }

    /*protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=NguyenDucHung\\SQLEXPRESS;Initial Catalog=VirtualTryonWomenFashion;Persist Security Info=True;User ID=sa;Password=12345;Encrypt=True");*/

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {

        if (!optionsBuilder.IsConfigured)
        {

            var config = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            string ConnectionStr = config.GetConnectionString("DefaultConnectionStringDB");

            optionsBuilder.UseSqlServer(ConnectionStr);
        }

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aiconversation>(entity =>
        {
            entity.HasKey(e => e.AiconversationId).HasName("PK__AIConver__6604C7D2D3192EC0");

            entity.ToTable("AIConversations");

            entity.Property(e => e.AiconversationId).HasColumnName("AIConversationID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Aiconversations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AIConversations_User");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__Carts__51BCD7978010E691");

            entity.Property(e => e.CartId).HasColumnName("CartID");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.IsDelete).HasDefaultValue(false);
            entity.Property(e => e.ProductVariantId)
                .IsRequired()
                .HasMaxLength(140)
                .IsUnicode(false)
                .HasColumnName("ProductVariantID");
            entity.Property(e => e.TryOnSlotId).HasColumnName("TryOnSlotID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ProductVariant).WithMany(p => p.Carts)
                .HasForeignKey(d => d.ProductVariantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Carts__ProductVa__22751F6C");

            entity.HasOne(d => d.TryOnSlot).WithMany(p => p.Carts)
                .HasForeignKey(d => d.TryOnSlotId)
                .HasConstraintName("FK__Carts__TryOnSlot__236943A5");

            entity.HasOne(d => d.User).WithMany(p => p.Carts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Carts__UserID__2180FB33");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A2BD172FF2C");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.BodyPart).HasMaxLength(50);
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CategorySlug)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<CategorySizeTemplate>(entity =>
        {
            entity.HasKey(e => e.TemplateId).HasName("PK__Category__F87ADD078A04E9EC");

            entity.HasIndex(e => new { e.CategoryId, e.SizeId }, "UQ_Category_Size").IsUnique();

            entity.Property(e => e.TemplateId).HasColumnName("TemplateID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.SizeId).HasColumnName("SizeID");

            entity.HasOne(d => d.Category).WithMany(p => p.CategorySizeTemplates)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CategorySizeTemplates_Categories");

            entity.HasOne(d => d.Size).WithMany(p => p.CategorySizeTemplates)
                .HasForeignKey(d => d.SizeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CategorySizeTemplates_Sizes");
        });

        modelBuilder.Entity<Characteristic>(entity =>
        {
            entity.HasKey(e => e.CharacteristicId).HasName("PK__Characte__C0EA4DAF7D9CE95C");

            entity.HasIndex(e => e.UserId, "UQ__Characte__1788CCAD53F42BCF").IsUnique();

            entity.Property(e => e.CharacteristicId).HasColumnName("CharacteristicID");
            entity.Property(e => e.OccasionNote).HasMaxLength(255);
            entity.Property(e => e.OccasionPreferenceId).HasColumnName("OccasionPreferenceID");
            entity.Property(e => e.SkinToneId).HasColumnName("SkinToneID");
            entity.Property(e => e.SkinToneNote).HasMaxLength(255);
            entity.Property(e => e.StyleTypeId).HasColumnName("StyleTypeID");
            entity.Property(e => e.StyleTypeNote).HasMaxLength(255);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.OccasionPreference).WithMany(p => p.Characteristics)
                .HasForeignKey(d => d.OccasionPreferenceId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Characteristics_OccasionPreference");

            entity.HasOne(d => d.SkinTone).WithMany(p => p.Characteristics)
                .HasForeignKey(d => d.SkinToneId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Characteristics_SkinTone");

            entity.HasOne(d => d.StyleType).WithMany(p => p.Characteristics)
                .HasForeignKey(d => d.StyleTypeId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_Characteristics_StyleType");

            entity.HasOne(d => d.User).WithOne(p => p.Characteristic)
                .HasForeignKey<Characteristic>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Character__UserI__245D67DE");
        });

        modelBuilder.Entity<Color>(entity =>
        {
            entity.HasKey(e => e.ColorId).HasName("PK__Color__8DA7676D734DF163");

            entity.ToTable("Color");

            entity.HasIndex(e => e.ColorPrefix, "UQ__Color__4DAF3239BE7C0A11").IsUnique();

            entity.Property(e => e.ColorId).HasColumnName("ColorID");
            entity.Property(e => e.ColorName).HasMaxLength(50);
            entity.Property(e => e.ColorPrefix)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.HexCode).HasMaxLength(20);
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Messages__C87C037CEEC51660");

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.AiconversationId).HasColumnName("AIConversationID");
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IsAiresponse).HasColumnName("IsAIResponse");
            entity.Property(e => e.ReceiverId).HasColumnName("ReceiverID");
            entity.Property(e => e.SenderId).HasColumnName("SenderID");
            entity.Property(e => e.TicketChatId).HasColumnName("TicketChatID");

            entity.HasOne(d => d.Aiconversation).WithMany(p => p.Messages)
                .HasForeignKey(d => d.AiconversationId)
                .HasConstraintName("FK_Messages_AIConversation");

            entity.HasOne(d => d.Receiver).WithMany(p => p.MessageReceivers)
                .HasForeignKey(d => d.ReceiverId)
                .HasConstraintName("FK_Messages_Receiver");

            entity.HasOne(d => d.Sender).WithMany(p => p.MessageSenders)
                .HasForeignKey(d => d.SenderId)
                .HasConstraintName("FK_Messages_Sender");

            entity.HasOne(d => d.TicketChat).WithMany(p => p.Messages)
                .HasForeignKey(d => d.TicketChatId)
                .HasConstraintName("FK_Messages_TicketChat");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E3285EEDAAB");

            entity.Property(e => e.NotificationId).HasColumnName("NotificationID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IsRead).HasDefaultValue(false);
            entity.Property(e => e.ReadAt).HasColumnType("datetime");
            entity.Property(e => e.ReceiverId).HasColumnName("ReceiverID");
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.Receiver).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.ReceiverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notificat__Recei__2BFE89A6");
        });

        modelBuilder.Entity<OccasionPreference>(entity =>
        {
            entity.HasKey(e => e.OccasionPreferenceId).HasName("PK__Occasion__6C177F6D2C193397");

            entity.Property(e => e.OccasionPreferenceId).HasColumnName("OccasionPreferenceID");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.OccasionPreferenceName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAFB7434B31");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.DeliveredAt).HasColumnType("datetime");
            entity.Property(e => e.DistrictId).HasColumnName("DistrictID");
            entity.Property(e => e.EstimatedDelivery).HasColumnType("datetime");
            entity.Property(e => e.InsuranceFee).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PackageHeight).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PackageLength).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PackageWeight).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PackageWidth).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaymentUrl).IsUnicode(false);
            entity.Property(e => e.ProvinceId).HasColumnName("ProvinceID");
            entity.Property(e => e.ReceiverAddress).HasMaxLength(500);
            entity.Property(e => e.ReceiverName).HasMaxLength(255);
            entity.Property(e => e.ReceiverPhone).HasMaxLength(50);
            entity.Property(e => e.ShippingCode).HasMaxLength(100);
            entity.Property(e => e.ShippingMoney).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.WardCode).HasMaxLength(100);

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Customers");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK__OrderDet__D3B9D30CF7B57B23");

            entity.Property(e => e.OrderDetailId).HasColumnName("OrderDetailID");
            entity.Property(e => e.CampaignId).HasColumnName("CampaignID");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.PriceAtTime).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ProductVariantId)
                .IsRequired()
                .HasMaxLength(140)
                .IsUnicode(false)
                .HasColumnName("ProductVariantID");

            entity.HasOne(d => d.Campaign).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.CampaignId)
                .HasConstraintName("FK__OrderDeta__Campa__2EDAF651");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Order__2CF2ADDF");

            entity.HasOne(d => d.ProductVariant).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductVariantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Produ__2DE6D218");
        });

        modelBuilder.Entity<OrderRefund>(entity =>
        {
            entity.HasKey(e => e.OrderRefundId).HasName("PK__OrderRef__9273F2410B96D868");

            entity.ToTable("OrderRefund");

            entity.Property(e => e.OrderRefundId).HasColumnName("OrderRefundID");
            entity.Property(e => e.AttemptNumber).HasDefaultValue(1);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.CustomerReason).IsRequired();
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.RefundAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ShippingCode).HasMaxLength(100);
            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Customer).WithMany(p => p.OrderRefundCustomers)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderRefund_Customer");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderRefunds)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderRefund_Orders");

            entity.HasOne(d => d.Staff).WithMany(p => p.OrderRefundStaffs)
                .HasForeignKey(d => d.StaffId)
                .HasConstraintName("FK_OrderRefund_Staff");
        });

        modelBuilder.Entity<OrderRefundDetail>(entity =>
        {
            entity.HasKey(e => e.OrderRefundDetailId).HasName("PK__OrderRef__681DAAAAF28FF7C9");

            entity.ToTable("OrderRefundDetail");

            entity.Property(e => e.OrderRefundDetailId).HasColumnName("OrderRefundDetailID");
            entity.Property(e => e.OrderDetailId).HasColumnName("OrderDetailID");
            entity.Property(e => e.OrderRefundId).HasColumnName("OrderRefundID");
            entity.Property(e => e.RefundPriceAtTime).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.OrderRefundDetails)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderRefundDetail_OrderDetail");

            entity.HasOne(d => d.OrderRefund).WithMany(p => p.OrderRefundDetails)
                .HasForeignKey(d => d.OrderRefundId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderRefundDetail_OrderRefund");
        });

        modelBuilder.Entity<OrderRefundImage>(entity =>
        {
            entity.HasKey(e => e.OrderRefundImageId).HasName("PK__OrderRef__10302D09E9AA2577");

            entity.ToTable("OrderRefundImage");

            entity.Property(e => e.OrderRefundImageId).HasColumnName("OrderRefundImageID");
            entity.Property(e => e.ImageUrl).IsRequired();
            entity.Property(e => e.OrderRefundId).HasColumnName("OrderRefundID");

            entity.HasOne(d => d.OrderRefund).WithMany(p => p.OrderRefundImages)
                .HasForeignKey(d => d.OrderRefundId)
                .HasConstraintName("FK_OrderRefundImage_OrderRefund");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__B40CC6ED6BC50C27");

            entity.HasIndex(e => e.ProductSlug, "UQ__Products__A8918E7078F1401C").IsUnique();

            entity.Property(e => e.ProductId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ProductSlug)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__Products__Catego__3D2915A8");

            entity.HasMany(d => d.Tags).WithMany(p => p.Products)
                .UsingEntity<Dictionary<string, object>>(
                    "ProductTag",
                    r => r.HasOne<Tag>().WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ProductTa__TagID__3F115E1A"),
                    l => l.HasOne<Product>().WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ProductTa__Produ__3E1D39E1"),
                    j =>
                    {
                        j.HasKey("ProductId", "TagId").HasName("PK__ProductT__625B0949723C05E5");
                        j.ToTable("ProductTags");
                        j.IndexerProperty<string>("ProductId")
                            .HasMaxLength(100)
                            .IsUnicode(false)
                            .HasColumnName("ProductID");
                        j.IndexerProperty<int>("TagId").HasColumnName("TagID");
                    });
        });

        modelBuilder.Entity<ProductColor>(entity =>
        {
            entity.HasKey(e => e.ProductColorId).HasName("PK__ProductC__C5DB681ECD2BE088");

            entity.Property(e => e.ProductColorId)
                .HasMaxLength(120)
                .IsUnicode(false)
                .HasColumnName("ProductColorID");
            entity.Property(e => e.ColorId).HasColumnName("ColorID");
            entity.Property(e => e.LensId)
                .IsUnicode(false)
                .HasColumnName("LensID");
            entity.Property(e => e.NoBgImgUrl).HasMaxLength(300);
            entity.Property(e => e.PackageLens).IsUnicode(false);
            entity.Property(e => e.ProductId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductID");

            entity.HasOne(d => d.Color).WithMany(p => p.ProductColors)
                .HasForeignKey(d => d.ColorId)
                .HasConstraintName("FK__ProductCo__Color__395884C4");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductColors)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__ProductCo__Produ__3864608B");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.ProductImageId).HasName("PK__ProductI__07B2B1D8DB4C9330");

            entity.Property(e => e.ProductImageId).HasColumnName("ProductImageID");
            entity.Property(e => e.ImageUrl).HasMaxLength(300);
            entity.Property(e => e.ProductColorId)
                .HasMaxLength(120)
                .IsUnicode(false)
                .HasColumnName("ProductColorID");

            entity.HasOne(d => d.ProductColor).WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.ProductColorId)
                .HasConstraintName("FK__ProductIm__Produ__3A4CA8FD");
        });

        modelBuilder.Entity<ProductInSaleCampaign>(entity =>
        {
            entity.HasKey(e => new { e.CampaignId, e.ProductId });

            entity.Property(e => e.CampaignId).HasColumnName("CampaignID");
            entity.Property(e => e.ProductId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductID");
            entity.Property(e => e.PercentDiscount).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.SalePrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Campaign).WithMany(p => p.ProductInSaleCampaigns)
                .HasForeignKey(d => d.CampaignId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductInSaleCampaigns_Campaign");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductInSaleCampaigns)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductInSaleCampaigns_Product");
        });

        modelBuilder.Entity<ProductVariant>(entity =>
        {
            entity.HasKey(e => e.ProductVariantId).HasName("PK__ProductV__E4D6672534FFC54E");

            entity.Property(e => e.ProductVariantId)
                .HasMaxLength(140)
                .IsUnicode(false)
                .HasColumnName("ProductVariantID");
            entity.Property(e => e.ImageUrl).HasMaxLength(300);
            entity.Property(e => e.ProductColorId)
                .HasMaxLength(120)
                .IsUnicode(false)
                .HasColumnName("ProductColorID");
            entity.Property(e => e.ProductHeight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductLength).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductWeight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductWidth).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Quantity).HasDefaultValue(0);
            entity.Property(e => e.SizeId).HasColumnName("SizeID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.VariantName).HasMaxLength(200);

            entity.HasOne(d => d.ProductColor).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.ProductColorId)
                .HasConstraintName("FK__ProductVa__Produ__40058253");

            entity.HasOne(d => d.Size).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.SizeId)
                .HasConstraintName("FK__ProductVa__SizeI__40F9A68C");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PK__Ratings__FCCDF85CEAE15339");

            entity.Property(e => e.RatingId).HasColumnName("RatingID");
            entity.Property(e => e.CreateAt).HasColumnType("datetime");
            entity.Property(e => e.OrderDetailId).HasColumnName("OrderDetailID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ratings__OrderDe__42E1EEFE");

            entity.HasOne(d => d.User).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ratings__UserID__41EDCAC5");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3A96CB1259");

            entity.Property(e => e.RoleId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("RoleID");
            entity.Property(e => e.RoleDescVn)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("RoleDescVN");
        });

        modelBuilder.Entity<SaleCampaign>(entity =>
        {
            entity.HasKey(e => e.CampaignId).HasName("PK__SaleCamp__3F5E8D79637C074F");

            entity.Property(e => e.CampaignId).HasColumnName("CampaignID");
            entity.Property(e => e.CampaignName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(300);
            entity.Property(e => e.Status).HasMaxLength(50);
        });

        modelBuilder.Entity<Size>(entity =>
        {
            entity.HasKey(e => e.SizeId).HasName("PK__Size__83BD095A9B1D6457");

            entity.ToTable("Size");

            entity.Property(e => e.SizeId).HasColumnName("SizeID");
            entity.Property(e => e.SizeCode).HasMaxLength(10);
        });

        modelBuilder.Entity<SkinTone>(entity =>
        {
            entity.HasKey(e => e.SkinToneId).HasName("PK__SkinTone__9FEA0FCBBDDC4EC3");

            entity.Property(e => e.SkinToneId).HasColumnName("SkinToneID");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.SkinToneName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<StatusLog>(entity =>
        {
            entity.HasKey(e => e.StatusLogId).HasName("PK__StatusLo__A1B4D0BDE23996AF");

            entity.Property(e => e.StatusLogId).HasColumnName("StatusLogID");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithMany(p => p.StatusLogs)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StatusLog__Order__43D61337");
        });

        modelBuilder.Entity<StyleType>(entity =>
        {
            entity.HasKey(e => e.StyleTypeId).HasName("PK__StyleTyp__81B6F4502D360030");

            entity.Property(e => e.StyleTypeId).HasColumnName("StyleTypeID");
            entity.Property(e => e.ImageUrl)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.StyleTypeName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<SuggestedOutfit>(entity =>
        {
            entity.HasKey(e => e.SuggestedOutfitId).HasName("PK__Suggeste__304834102D80B27A");

            entity.Property(e => e.SuggestedOutfitId).HasColumnName("SuggestedOutfitID");
            entity.Property(e => e.AiconversationId).HasColumnName("AIConversationID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Reason).HasMaxLength(255);

            entity.HasOne(d => d.Aiconversation).WithMany(p => p.SuggestedOutfits)
                .HasForeignKey(d => d.AiconversationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SuggestedOutfits_AIConversation");

            entity.HasMany(d => d.ProductVariants).WithMany(p => p.SuggestedOutfits)
                .UsingEntity<Dictionary<string, object>>(
                    "OutfitVariant",
                    r => r.HasOne<ProductVariant>().WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_OutfitVariances_ProductVariant"),
                    l => l.HasOne<SuggestedOutfit>().WithMany()
                        .HasForeignKey("SuggestedOutfitId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_OutfitVariances_SuggestedOutfit"),
                    j =>
                    {
                        j.HasKey("SuggestedOutfitId", "ProductVariantId").HasName("PK__OutfitVa__7E055262F703E592");
                        j.ToTable("OutfitVariants");
                        j.IndexerProperty<int>("SuggestedOutfitId").HasColumnName("SuggestedOutfitID");
                        j.IndexerProperty<string>("ProductVariantId")
                            .HasMaxLength(140)
                            .IsUnicode(false)
                            .HasColumnName("ProductVariantID");
                    });
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("PK__Tags__657CFA4C932E6E50");

            entity.Property(e => e.TagId).HasColumnName("TagID");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TicketChat>(entity =>
        {
            entity.HasKey(e => e.TicketChatId).HasName("PK__TicketCh__F9115A616941FEE8");

            entity.HasIndex(e => e.Slug, "UQ__TicketCh__BC7B5FB6AC42BE58").IsUnique();

            entity.Property(e => e.TicketChatId).HasColumnName("TicketChatID");
            entity.Property(e => e.ClosedAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.Slug).HasMaxLength(255);
            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Customer).WithMany(p => p.TicketChatCustomers)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TicketChats_Customer");

            entity.HasOne(d => d.Staff).WithMany(p => p.TicketChatStaffs)
                .HasForeignKey(d => d.StaffId)
                .HasConstraintName("FK_TicketChats_Staff");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__Transact__55433A4B22CF85B6");

            entity.HasIndex(e => e.OrderId, "UQ_Transactions_OrderID")
                .IsUnique()
                .HasFilter("([OrderID] IS NOT NULL)");

            entity.HasIndex(e => e.OrderRefundId, "UQ_Transactions_OrderRefundID")
                .IsUnique()
                .HasFilter("([OrderRefundID] IS NOT NULL)");

            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Method).HasMaxLength(100);
            entity.Property(e => e.Money).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.OrderRefundId).HasColumnName("OrderRefundID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.ThirdPartyCode).HasMaxLength(255);
            entity.Property(e => e.ThirdPartyOrderIdCode).HasMaxLength(255);
            entity.Property(e => e.Type).HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.WalletId).HasColumnName("WalletID");

            entity.HasOne(d => d.Order).WithOne(p => p.Transaction)
                .HasForeignKey<Transaction>(d => d.OrderId)
                .HasConstraintName("FK_Transactions_Orders");

            entity.HasOne(d => d.OrderRefund).WithOne(p => p.Transaction)
                .HasForeignKey<Transaction>(d => d.OrderRefundId)
                .HasConstraintName("FK_Transactions_OrderRefund");

            entity.HasOne(d => d.User).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transactions_Users");

            entity.HasOne(d => d.Wallet).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.WalletId)
                .HasConstraintName("FK_Transactions_Wallet");
        });

        modelBuilder.Entity<TryOnSlot>(entity =>
        {
            entity.HasKey(e => e.TryOnSlotId).HasName("PK__TryOnSlo__9581D25EB66A4AE2");

            entity.Property(e => e.TryOnSlotId).HasColumnName("TryOnSlotID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.OutputTaskId)
                .HasMaxLength(250)
                .HasColumnName("OutputTaskID");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UploadImageUrl).HasMaxLength(255);

            entity.HasOne(d => d.Customer).WithMany(p => p.TryOnSlots)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TryOnSlots_Customer");

            entity.HasMany(d => d.ProductColors).WithMany(p => p.TryOnSlots)
                .UsingEntity<Dictionary<string, object>>(
                    "TryOnVariantClothe",
                    r => r.HasOne<ProductColor>().WithMany()
                        .HasForeignKey("ProductColorId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__TryOnVari__Produ__4D5F7D71"),
                    l => l.HasOne<TryOnSlot>().WithMany()
                        .HasForeignKey("TryOnSlotId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__TryOnVari__TryOn__4C6B5938"),
                    j =>
                    {
                        j.HasKey("TryOnSlotId", "ProductColorId").HasName("PK__TryOnVar__69DC64DF91A06A4A");
                        j.ToTable("TryOnVariantClothes");
                        j.IndexerProperty<int>("TryOnSlotId").HasColumnName("TryOnSlotID");
                        j.IndexerProperty<string>("ProductColorId")
                            .HasMaxLength(120)
                            .IsUnicode(false)
                            .HasColumnName("ProductColorID");
                    });
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC1D62D8C9");

            entity.HasIndex(e => e.WalletId, "UQ_Users_WalletID")
                .IsUnique()
                .HasFilter("([WalletID] IS NOT NULL)");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534196290F9").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmailConfirmToken)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsEmailConfirm).HasDefaultValue(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.RoleId)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("RoleID");
            entity.Property(e => e.WalletId).HasColumnName("WalletID");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__RoleID__503BEA1C");

            entity.HasOne(d => d.Wallet).WithOne(p => p.User)
                .HasForeignKey<User>(d => d.WalletId)
                .HasConstraintName("FK_Users_Wallet");
        });

        modelBuilder.Entity<UserInteraction>(entity =>
        {
            entity.HasKey(e => e.UserInteractionId).HasName("PK__UserInte__2CD47CC5BB97F324");

            entity.Property(e => e.UserInteractionId).HasColumnName("UserInteractionID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.InteractionType).HasMaxLength(100);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Weight).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.UserInteractions)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserInteractions_Product");

            entity.HasOne(d => d.User).WithMany(p => p.UserInteractions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserInteractions_User");
        });

        modelBuilder.Entity<Wallet>(entity =>
        {
            entity.HasKey(e => e.WalletId).HasName("PK__Wallet__84D4F92E243D3035");

            entity.ToTable("Wallet");

            entity.Property(e => e.WalletId).HasColumnName("WalletID");
            entity.Property(e => e.Balance)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Wishlist>(entity =>
        {
            entity.HasKey(e => e.WishlistId).HasName("PK__Wishlist__233189CB66F3F117");

            entity.Property(e => e.WishlistId).HasColumnName("WishlistID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Product).WithMany(p => p.Wishlists)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wishlists_ProductVariants");

            entity.HasOne(d => d.User).WithMany(p => p.Wishlists)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wishlists_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}