// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using VirtualTryonWomenFashion.Data.Models;

namespace VirtualTryonWomenFashion.Data.DBContext;

public partial class VirtualTryonWomenFashionContext : DbContext
{
    public VirtualTryonWomenFashionContext()
    {
    }

    public VirtualTryonWomenFashionContext(DbContextOptions<VirtualTryonWomenFashionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Aiconversation> Aiconversations { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Characteristic> Characteristics { get; set; }

    public virtual DbSet<Color> Colors { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductColor> ProductColors { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductInSaleCampaign> ProductInSaleCampaigns { get; set; }

    public virtual DbSet<ProductVariant> ProductVariants { get; set; }

    public virtual DbSet<Rating> Ratings { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SaleCampaign> SaleCampaigns { get; set; }

    public virtual DbSet<Size> Sizes { get; set; }

    public virtual DbSet<StatusLog> StatusLogs { get; set; }

    public virtual DbSet<SuggestedOutfit> SuggestedOutfits { get; set; }

    public virtual DbSet<TicketChat> TicketChats { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<TryOnSlot> TryOnSlots { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserInteraction> UserInteractions { get; set; }

    public virtual DbSet<Wishlist> Wishlists { get; set; }

    /*protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=NguyenDucHung\\SQLEXPRESS;Initial Catalog=VirtualTryonWomenFashion;Persist Security Info=True;User ID=sa;Password=12345");*/

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {

        if (!optionsBuilder.IsConfigured)
        {

            var config = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
            string ConnectionStr = config.GetConnectionString("DefaultConnectionStringDB");

            optionsBuilder.UseSqlServer(ConnectionStr);
        }

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aiconversation>(entity =>
        {
            entity.HasKey(e => e.AiconversationId).HasName("PK__AIConver__6604C7D29B412FE2");

            entity.ToTable("AIConversations");

            entity.Property(e => e.AiconversationId).HasColumnName("AIConversationID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Aiconversations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AIConversations_User");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__Carts__51BCD7976F205798");

            entity.Property(e => e.CartId).HasColumnName("CartID");
            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.IsDelete).HasDefaultValue(false);
            entity.Property(e => e.ProductVariantId)
                .IsRequired()
                .HasMaxLength(140)
                .IsUnicode(false)
                .HasColumnName("ProductVariantID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ProductVariant).WithMany(p => p.Carts)
                .HasForeignKey(d => d.ProductVariantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Carts__ProductVa__18EBB532");

            entity.HasOne(d => d.User).WithMany(p => p.Carts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Carts__UserID__17F790F9");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A2BA8B53575");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.BodyPart).HasMaxLength(50);
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CategorySlug)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Characteristic>(entity =>
        {
            entity.HasKey(e => e.CharacteristicId).HasName("PK__Characte__C0EA4DAF4968F81D");

            entity.Property(e => e.CharacteristicId).HasColumnName("CharacteristicID");
            entity.Property(e => e.ColorPreference).HasMaxLength(100);
            entity.Property(e => e.Height).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.OccasionPreference).HasMaxLength(100);
            entity.Property(e => e.SkinTone).HasMaxLength(50);
            entity.Property(e => e.StyleType).HasMaxLength(100);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.User).WithMany(p => p.Characteristics)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Character__UserI__3F466844");
        });

        modelBuilder.Entity<Color>(entity =>
        {
            entity.HasKey(e => e.ColorId).HasName("PK__Color__8DA7676D4DD31480");

            entity.ToTable("Color");

            entity.HasIndex(e => e.ColorPrefix, "UQ__Color__4DAF323902A23332").IsUnique();

            entity.Property(e => e.ColorId).HasColumnName("ColorID");
            entity.Property(e => e.ColorName).HasMaxLength(50);
            entity.Property(e => e.ColorPrefix)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.HexCode).HasMaxLength(20);
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Messages__C87C037CF7AD7356");

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.AiconversationId).HasColumnName("AIConversationID");
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IsAiresponse).HasColumnName("IsAIResponse");
            entity.Property(e => e.ReceiverId).HasColumnName("ReceiverID");
            entity.Property(e => e.SenderId).HasColumnName("SenderID");
            entity.Property(e => e.TicketChatId).HasColumnName("TicketChatID");

            entity.HasOne(d => d.Aiconversation).WithMany(p => p.Messages)
                .HasForeignKey(d => d.AiconversationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Messages_AIConversation");

            entity.HasOne(d => d.Receiver).WithMany(p => p.MessageReceivers)
                .HasForeignKey(d => d.ReceiverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Messages_Receiver");

            entity.HasOne(d => d.Sender).WithMany(p => p.MessageSenders)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Messages_Sender");

            entity.HasOne(d => d.TicketChat).WithMany(p => p.Messages)
                .HasForeignKey(d => d.TicketChatId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Messages_TicketChat");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E32BD847362");

            entity.Property(e => e.NotificationId).HasColumnName("NotificationID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IsRead).HasDefaultValue(false);
            entity.Property(e => e.ReadAt).HasColumnType("datetime");
            entity.Property(e => e.ReceiverId).HasColumnName("ReceiverID");
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.Receiver).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.ReceiverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notificat__Recei__4316F928");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAF0B3B58DF");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.DiscountMoney).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.EstimatedDelivery).HasColumnType("datetime");
            entity.Property(e => e.PackageHeight).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PackageLength).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PackageWeight).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PackageWidth).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ReceiverAddress).HasMaxLength(500);
            entity.Property(e => e.ReceiverName).HasMaxLength(255);
            entity.Property(e => e.ReceiverPhone).HasMaxLength(50);
            entity.Property(e => e.ShippingCode).HasMaxLength(100);
            entity.Property(e => e.ShippingMoney).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Customers");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK__OrderDet__D3B9D30C1EE52755");

            entity.Property(e => e.OrderDetailId).HasColumnName("OrderDetailID");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.PriceAtTime).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ProductVariantId)
                .IsRequired()
                .HasMaxLength(140)
                .IsUnicode(false)
                .HasColumnName("ProductVariantID");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Order__07C12930");

            entity.HasOne(d => d.ProductVariant).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductVariantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderDeta__Produ__08B54D69");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__B40CC6ED67EC47EB");

            entity.HasIndex(e => e.ProductSlug, "UQ__Products__A8918E7094FE9AEE").IsUnique();

            entity.Property(e => e.ProductId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ProductSlug)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK__Products__Catego__49C3F6B7");
        });

        modelBuilder.Entity<ProductColor>(entity =>
        {
            entity.HasKey(e => e.ProductColorId).HasName("PK__ProductC__C5DB681E67F1DD2B");

            entity.Property(e => e.ProductColorId)
                .HasMaxLength(120)
                .IsUnicode(false)
                .HasColumnName("ProductColorID");
            entity.Property(e => e.ColorId).HasColumnName("ColorID");
            entity.Property(e => e.LensId)
                .IsUnicode(false)
                .HasColumnName("LensID");
            entity.Property(e => e.ProductId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductID");

            entity.HasOne(d => d.Color).WithMany(p => p.ProductColors)
                .HasForeignKey(d => d.ColorId)
                .HasConstraintName("FK__ProductCo__Color__5070F446");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductColors)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__ProductCo__Produ__4F7CD00D");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.ProductImageId).HasName("PK__ProductI__07B2B1D8462EFB0B");

            entity.Property(e => e.ProductImageId).HasColumnName("ProductImageID");
            entity.Property(e => e.ImageUrl).HasMaxLength(300);
            entity.Property(e => e.ProductColorId)
                .HasMaxLength(120)
                .IsUnicode(false)
                .HasColumnName("ProductColorID");

            entity.HasOne(d => d.ProductColor).WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.ProductColorId)
                .HasConstraintName("FK__ProductIm__Produ__534D60F1");
        });

        modelBuilder.Entity<ProductInSaleCampaign>(entity =>
        {
            entity.HasKey(e => new { e.CampaignId, e.ProductId });

            entity.Property(e => e.CampaignId).HasColumnName("CampaignID");
            entity.Property(e => e.ProductId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductID");
            entity.Property(e => e.PercentDiscount).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.SalePrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Campaign).WithMany(p => p.ProductInSaleCampaigns)
                .HasForeignKey(d => d.CampaignId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductInSaleCampaigns_Campaign");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductInSaleCampaigns)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductInSaleCampaigns_Product");
        });

        modelBuilder.Entity<ProductVariant>(entity =>
        {
            entity.HasKey(e => e.ProductVariantId).HasName("PK__ProductV__E4D667258C11C23A");

            entity.Property(e => e.ProductVariantId)
                .HasMaxLength(140)
                .IsUnicode(false)
                .HasColumnName("ProductVariantID");
            entity.Property(e => e.ImageUrl).HasMaxLength(300);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductColorId)
                .HasMaxLength(120)
                .IsUnicode(false)
                .HasColumnName("ProductColorID");
            entity.Property(e => e.ProductHeight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductLength).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductWeight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ProductWidth).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Quantity).HasDefaultValue(0);
            entity.Property(e => e.SizeId).HasColumnName("SizeID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.VariantName).HasMaxLength(200);

            entity.HasOne(d => d.ProductColor).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.ProductColorId)
                .HasConstraintName("FK__ProductVa__Produ__5812160E");

            entity.HasOne(d => d.Size).WithMany(p => p.ProductVariants)
                .HasForeignKey(d => d.SizeId)
                .HasConstraintName("FK__ProductVa__SizeI__59063A47");
        });

        modelBuilder.Entity<Rating>(entity =>
        {
            entity.HasKey(e => e.RatingId).HasName("PK__Ratings__FCCDF85C0B0E86A0");

            entity.Property(e => e.RatingId).HasColumnName("RatingID");
            entity.Property(e => e.CreateAt).HasColumnType("datetime");
            entity.Property(e => e.OrderDetailId).HasColumnName("OrderDetailID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.OrderDetail).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.OrderDetailId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ratings__OrderDe__14270015");

            entity.HasOne(d => d.User).WithMany(p => p.Ratings)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Ratings__UserID__1332DBDC");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3AF4513EEB");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<SaleCampaign>(entity =>
        {
            entity.HasKey(e => e.CampaignId).HasName("PK__SaleCamp__3F5E8D795D97C317");

            entity.Property(e => e.CampaignId).HasColumnName("CampaignID");
            entity.Property(e => e.CampaignName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Status).HasMaxLength(50);
        });

        modelBuilder.Entity<Size>(entity =>
        {
            entity.HasKey(e => e.SizeId).HasName("PK__Size__83BD095AB3D0526E");

            entity.ToTable("Size");

            entity.Property(e => e.SizeId).HasColumnName("SizeID");
            entity.Property(e => e.SizeCode).HasMaxLength(10);
        });

        modelBuilder.Entity<StatusLog>(entity =>
        {
            entity.HasKey(e => e.StatusLogId).HasName("PK__StatusLo__A1B4D0BDF0168BA5");

            entity.Property(e => e.StatusLogId).HasColumnName("StatusLogID");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdateDate).HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithMany(p => p.StatusLogs)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__StatusLog__Order__0B91BA14");
        });

        modelBuilder.Entity<SuggestedOutfit>(entity =>
        {
            entity.HasKey(e => e.SuggestedOutfitId).HasName("PK__Suggeste__304834105C0F94BE");

            entity.Property(e => e.SuggestedOutfitId).HasColumnName("SuggestedOutfitID");
            entity.Property(e => e.AiconversationId).HasColumnName("AIConversationID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Aiconversation).WithMany(p => p.SuggestedOutfits)
                .HasForeignKey(d => d.AiconversationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SuggestedOutfits_AIConversation");

            entity.HasMany(d => d.ProductVariants).WithMany(p => p.SuggestedOutfits)
                .UsingEntity<Dictionary<string, object>>(
                    "OutfitVariant",
                    r => r.HasOne<ProductVariant>().WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_OutfitVariances_ProductVariant"),
                    l => l.HasOne<SuggestedOutfit>().WithMany()
                        .HasForeignKey("SuggestedOutfitId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_OutfitVariances_SuggestedOutfit"),
                    j =>
                    {
                        j.HasKey("SuggestedOutfitId", "ProductVariantId").HasName("PK__OutfitVa__7E055262EA8FD1AD");
                        j.ToTable("OutfitVariants");
                        j.IndexerProperty<int>("SuggestedOutfitId").HasColumnName("SuggestedOutfitID");
                        j.IndexerProperty<string>("ProductVariantId")
                            .HasMaxLength(140)
                            .IsUnicode(false)
                            .HasColumnName("ProductVariantID");
                    });
        });

        modelBuilder.Entity<TicketChat>(entity =>
        {
            entity.HasKey(e => e.TicketChatId).HasName("PK__TicketCh__F9115A613C765532");

            entity.HasIndex(e => e.Slug, "UQ__TicketCh__BC7B5FB66E7F4C6D").IsUnique();

            entity.Property(e => e.TicketChatId).HasColumnName("TicketChatID");
            entity.Property(e => e.ClosedAt).HasColumnType("datetime");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.Slug).HasMaxLength(255);
            entity.Property(e => e.StaffId).HasColumnName("StaffID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Customer).WithMany(p => p.TicketChatCustomers)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TicketChats_Customer");

            entity.HasOne(d => d.Staff).WithMany(p => p.TicketChatStaffs)
                .HasForeignKey(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TicketChats_Staff");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__Transact__55433A4B959D846B");

            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Method).HasMaxLength(100);
            entity.Property(e => e.Money).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.ThirdPartyCode).HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Order).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transactions_Orders");

            entity.HasOne(d => d.User).WithMany(p => p.Transactions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transactions_Users");
        });

        modelBuilder.Entity<TryOnSlot>(entity =>
        {
            entity.HasKey(e => e.TryOnSlotId).HasName("PK__TryOnSlo__9581D25E7F2F34F5");

            entity.Property(e => e.TryOnSlotId).HasColumnName("TryOnSlotID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.DeletedAt).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.OutputImageUrl).HasMaxLength(255);
            entity.Property(e => e.OutputTaskId).HasColumnName("OutputTaskID");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.UploadImageUrl).HasMaxLength(255);

            entity.HasOne(d => d.Customer).WithMany(p => p.TryOnSlots)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TryOnSlots_Customer");

            entity.HasMany(d => d.ProductVariants).WithMany(p => p.TryOnSlots)
                .UsingEntity<Dictionary<string, object>>(
                    "TryOnVariantClothe",
                    r => r.HasOne<ProductVariant>().WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__TryOnVari__Produ__1CBC4616"),
                    l => l.HasOne<TryOnSlot>().WithMany()
                        .HasForeignKey("TryOnSlotId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__TryOnVari__TryOn__1BC821DD"),
                    j =>
                    {
                        j.HasKey("TryOnSlotId", "ProductVariantId").HasName("PK__TryOnVar__DBCCB42C6E3B7A86");
                        j.ToTable("TryOnVariantClothes");
                        j.IndexerProperty<int>("TryOnSlotId").HasColumnName("TryOnSlotID");
                        j.IndexerProperty<string>("ProductVariantId")
                            .HasMaxLength(140)
                            .IsUnicode(false)
                            .HasColumnName("ProductVariantID");
                    });
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACEF142A4A");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534620CB246").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmailConfirmToken)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsEmailConfirm).HasDefaultValue(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Users__RoleID__3C69FB99");
        });

        modelBuilder.Entity<UserInteraction>(entity =>
        {
            entity.HasKey(e => e.UserInteractionId).HasName("PK__UserInte__2CD47CC56A52DBCF");

            entity.Property(e => e.UserInteractionId).HasColumnName("UserInteractionID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.InteractionType).HasMaxLength(100);
            entity.Property(e => e.ProductId)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Weight).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Product).WithMany(p => p.UserInteractions)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserInteractions_Product");

            entity.HasOne(d => d.User).WithMany(p => p.UserInteractions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserInteractions_User");
        });

        modelBuilder.Entity<Wishlist>(entity =>
        {
            entity.HasKey(e => e.WishlistId).HasName("PK__Wishlist__233189CB607F23B5");

            entity.Property(e => e.WishlistId).HasColumnName("WishlistID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ProductVariantId)
                .IsRequired()
                .HasMaxLength(140)
                .IsUnicode(false)
                .HasColumnName("ProductVariantID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.ProductVariant).WithMany(p => p.Wishlists)
                .HasForeignKey(d => d.ProductVariantId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wishlists_ProductVariants");

            entity.HasOne(d => d.User).WithMany(p => p.Wishlists)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wishlists_Users");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}