// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Aiconversation
{
    public int AiconversationId { get; set; }

    public int UserId { get; set; }

    public string CurrentUserStyleJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<SuggestedOutfit> SuggestedOutfits { get; set; } = new List<SuggestedOutfit>();

    public virtual User User { get; set; }
}