// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Cart
{
    public int CartId { get; set; }

    public int UserId { get; set; }

    public DateTime CreateDate { get; set; }

    public int Quantity { get; set; }

    public bool? IsDelete { get; set; }

    public string ProductVariantId { get; set; }

    public int? TryOnSlotId { get; set; }

    public virtual ProductVariant ProductVariant { get; set; }

    public virtual TryOnSlot TryOnSlot { get; set; }

    public virtual User User { get; set; }
}