// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class CategorySizeTemplate
{
    public int TemplateId { get; set; }

    public int CategoryId { get; set; }

    public int SizeId { get; set; }

    public double? MinShoulder { get; set; }

    public double? MaxShoulder { get; set; }

    public double? MinBust { get; set; }

    public double? MaxBust { get; set; }

    public double? MinWaist { get; set; }

    public double? MaxWaist { get; set; }

    public double? MinHips { get; set; }

    public double? MaxHips { get; set; }

    public virtual Category Category { get; set; }

    public virtual Size Size { get; set; }
}