// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Characteristic
{
    public int CharacteristicId { get; set; }

    public int UserId { get; set; }

    public decimal? Weight { get; set; }

    public int? Age { get; set; }

    public decimal? Height { get; set; }

    public string ColorPreference { get; set; }

    public string StyleType { get; set; }

    public string OccasionPreference { get; set; }

    public string SkinTone { get; set; }

    public virtual User User { get; set; }
}