// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Characteristic
{
    public int CharacteristicId { get; set; }

    public int UserId { get; set; }

    public double? Weight { get; set; }

    public int? Age { get; set; }

    public double? Height { get; set; }

    public double? Bust { get; set; }

    public double? Waist { get; set; }

    public double? Hips { get; set; }

    public string StyleTypeNote { get; set; }

    public string OccasionNote { get; set; }

    public string SkinToneNote { get; set; }

    public int? StyleTypeId { get; set; }

    public int? OccasionPreferenceId { get; set; }

    public int? SkinToneId { get; set; }

    public virtual OccasionPreference OccasionPreference { get; set; }

    public virtual SkinTone SkinTone { get; set; }

    public virtual StyleType StyleType { get; set; }

    public virtual User User { get; set; }
}