// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public int? TicketChatId { get; set; }

    public int? SenderId { get; set; }

    public int? ReceiverId { get; set; }

    public int? AiconversationId { get; set; }

    public bool IsAiresponse { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Aiconversation Aiconversation { get; set; }

    public virtual User Receiver { get; set; }

    public virtual User Sender { get; set; }

    public virtual TicketChat TicketChat { get; set; }
}