// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int ReceiverId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ReadAt { get; set; }

    public bool? IsRead { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public virtual User Receiver { get; set; }
}