// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class OccasionPreference
{
    public int OccasionPreferenceId { get; set; }

    public string OccasionPreferenceName { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<Characteristic> Characteristics { get; set; } = new List<Characteristic>();
}