// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class OrderRefundDetail
{
    public int OrderRefundDetailId { get; set; }

    public int OrderRefundId { get; set; }

    public int OrderDetailId { get; set; }

    public int Quantity { get; set; }

    public decimal RefundPriceAtTime { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    public virtual OrderRefund OrderRefund { get; set; }
}