// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class OrderRefundImage
{
    public int OrderRefundImageId { get; set; }

    public int OrderRefundId { get; set; }

    public string ImageUrl { get; set; }

    public virtual OrderRefund OrderRefund { get; set; }
}