// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class OrderDetail
{
    public int OrderDetailId { get; set; }

    public int OrderId { get; set; }

    public string ProductVariantId { get; set; }

    public int Quantity { get; set; }

    public decimal PriceAtTime { get; set; }

    public int? CampaignId { get; set; }

    public virtual SaleCampaign Campaign { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderRefundDetail> OrderRefundDetails { get; set; } = new List<OrderRefundDetail>();

    public virtual ProductVariant ProductVariant { get; set; }

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();
}