// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public string ReceiverName { get; set; }

    public string ReceiverPhone { get; set; }

    public string ReceiverAddress { get; set; }

    public int? ProvinceId { get; set; }

    public int? DistrictId { get; set; }

    public string WardCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public decimal? Amount { get; set; }

    public string Note { get; set; }

    public decimal? PackageWeight { get; set; }

    public decimal? PackageHeight { get; set; }

    public decimal? PackageWidth { get; set; }

    public decimal? PackageLength { get; set; }

    public decimal? ShippingMoney { get; set; }

    public decimal? InsuranceFee { get; set; }

    public string ShippingCode { get; set; }

    public DateTime? EstimatedDelivery { get; set; }

    public string PaymentUrl { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public string DeliveringType { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderRefund> OrderRefunds { get; set; } = new List<OrderRefund>();

    public virtual ICollection<StatusLog> StatusLogs { get; set; } = new List<StatusLog>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}