// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class OrderRefund
{
    public int OrderRefundId { get; set; }

    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public int? StaffId { get; set; }

    public string CustomerReason { get; set; }

    public string StaffResponse { get; set; }

    public string Status { get; set; }

    public int AttemptNumber { get; set; }

    public decimal RefundAmount { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string ShippingCode { get; set; }

    public string DeliveringType { get; set; }

    public virtual User Customer { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<OrderRefundDetail> OrderRefundDetails { get; set; } = new List<OrderRefundDetail>();

    public virtual ICollection<OrderRefundImage> OrderRefundImages { get; set; } = new List<OrderRefundImage>();

    public virtual User Staff { get; set; }

    public virtual Transaction Transaction { get; set; }
}