// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class ProductInSaleCampaign
{
    public int CampaignId { get; set; }

    public int ProductId { get; set; }

    public decimal? PercentDiscount { get; set; }

    public decimal? SalePrice { get; set; }

    public virtual SaleCampaign Campaign { get; set; }

    public virtual Product Product { get; set; }
}