// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Product
{
    public string ProductId { get; set; }

    public string ProductName { get; set; }

    public string ProductSlug { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public bool? IsDeleted { get; set; }

    public string MainImageUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CategoryId { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ProductColor> ProductColors { get; set; } = new List<ProductColor>();

    public virtual ICollection<ProductInSaleCampaign> ProductInSaleCampaigns { get; set; } = new List<ProductInSaleCampaign>();

    public virtual ICollection<UserInteraction> UserInteractions { get; set; } = new List<UserInteraction>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}