// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class ProductVariant
{
    public string ProductVariantId { get; set; }

    public string ProductColorId { get; set; }

    public int? SizeId { get; set; }

    public string VariantName { get; set; }

    public int? Quantity { get; set; }

    public string ImageUrl { get; set; }

    public string Status { get; set; }

    public decimal? Price { get; set; }

    public decimal? ProductWeight { get; set; }

    public decimal? ProductLength { get; set; }

    public decimal? ProductWidth { get; set; }

    public decimal? ProductHeight { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ProductColor ProductColor { get; set; }

    public virtual Size Size { get; set; }

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();

    public virtual ICollection<SuggestedOutfit> SuggestedOutfits { get; set; } = new List<SuggestedOutfit>();

    public virtual ICollection<TryOnSlot> TryOnSlots { get; set; } = new List<TryOnSlot>();
}