// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class ProductColor
{
    public int ProductColorId { get; set; }

    public int? ProductId { get; set; }

    public int? ColorId { get; set; }

    public string LensId { get; set; }

    public virtual Color Color { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();
}