// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Rating
{
    public int RatingId { get; set; }

    public int? RatingValue { get; set; }

    public string Comment { get; set; }

    public DateTime? CreateAt { get; set; }

    public int UserId { get; set; }

    public int OrderDetailId { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    public virtual User User { get; set; }
}