// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class ShippingRegion
{
    public int ShippingRegionId { get; set; }

    public string RegionType { get; set; }

    public decimal BasePrice { get; set; }

    public decimal AdditionalWeightFee { get; set; }
}