// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class ShopAddress
{
    public int ShopAddressId { get; set; }

    public string ShopName { get; set; }

    public string ShopPhone { get; set; }

    public string ShopAddress1 { get; set; }

    public int? ProvinceId { get; set; }

    public int? DistrictId { get; set; }

    public string WardCode { get; set; }
}