// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Size
{
    public int SizeId { get; set; }

    public string SizeCode { get; set; }

    public double? MinHeight { get; set; }

    public double? MaxHeight { get; set; }

    public double? MinBust { get; set; }

    public double? MaxBust { get; set; }

    public double? MinWaist { get; set; }

    public double? MaxWaist { get; set; }

    public double? MinHips { get; set; }

    public double? MaxHips { get; set; }

    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();
}