// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class StatusLog
{
    public int StatusLogId { get; set; }

    public int OrderId { get; set; }

    public string Status { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual Order Order { get; set; }
}