// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class StyleType
{
    public int StyleTypeId { get; set; }

    public string StyleTypeName { get; set; }

    public string ImageUrl { get; set; }

    public virtual ICollection<Characteristic> Characteristics { get; set; } = new List<Characteristic>();
}