// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class SuggestedOutfit
{
    public int SuggestedOutfitId { get; set; }

    public int AiconversationId { get; set; }

    public string UserStyleJson { get; set; }

    public string Reason { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Aiconversation Aiconversation { get; set; }

    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();
}