// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class TicketChat
{
    public int TicketChatId { get; set; }

    public int CustomerId { get; set; }

    public int StaffId { get; set; }

    public string Slug { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ClosedAt { get; set; }

    public string Status { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual User Staff { get; set; }
}