// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int UserId { get; set; }

    public int? OrderId { get; set; }

    public int? OrderRefundId { get; set; }

    public int? WalletId { get; set; }

    public string Status { get; set; }

    public decimal? Money { get; set; }

    public string Method { get; set; }

    public string Type { get; set; }

    public string ThirdPartyCode { get; set; }

    public string ThirdPartyOrderIdCode { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderRefund OrderRefund { get; set; }

    public virtual User User { get; set; }

    public virtual Wallet Wallet { get; set; }
}