// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class TryOnSlot
{
    public int TryOnSlotId { get; set; }

    public int CustomerId { get; set; }

    public string Name { get; set; }

    public string UploadImageUrl { get; set; }

    public string UploadImageBinary { get; set; }

    public string OutputImageUrl { get; set; }

    public string OutputTaskId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual User Customer { get; set; }

    public virtual ICollection<ProductColor> ProductColors { get; set; } = new List<ProductColor>();
}