// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class User
{
    public int UserId { get; set; }

    public string RoleId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Password { get; set; }

    public bool? IsActive { get; set; }

    public string Address { get; set; }

    public bool? IsEmailConfirm { get; set; }

    public DateTime CreatedDate { get; set; }

    public string EmailConfirmToken { get; set; }

    public virtual ICollection<Aiconversation> Aiconversations { get; set; } = new List<Aiconversation>();

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Characteristic> Characteristics { get; set; } = new List<Characteristic>();

    public virtual ICollection<Message> MessageReceivers { get; set; } = new List<Message>();

    public virtual ICollection<Message> MessageSenders { get; set; } = new List<Message>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual Role Role { get; set; }

    public virtual ICollection<TicketChat> TicketChatCustomers { get; set; } = new List<TicketChat>();

    public virtual ICollection<TicketChat> TicketChatStaffs { get; set; } = new List<TicketChat>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();

    public virtual ICollection<TryOnSlot> TryOnSlots { get; set; } = new List<TryOnSlot>();

    public virtual ICollection<UserInteraction> UserInteractions { get; set; } = new List<UserInteraction>();

    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}