// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class UserInteraction
{
    public int UserInteractionId { get; set; }

    public int UserId { get; set; }

    public int ProductId { get; set; }

    public string InteractionType { get; set; }

    public DateTime CreatedAt { get; set; }

    public decimal? Weight { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}