// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VirtualTryonWomenFashion.Data.Models;

public partial class Wishlist
{
    public int WishlistId { get; set; }

    public int UserId { get; set; }

    public string ProductVariantId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ProductVariant ProductVariant { get; set; }

    public virtual User User { get; set; }
}