import type { Metadata } from "next";
import { Geist, Geist_Mono, Frank_Ruhl_Libre } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Spin } from "antd";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { defaultToastContainerProps } from "@/helpers/toastHelper";
import { AuthProvider } from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const frankRuhlLibre = Frank_Ruhl_Libre({
  variable: "--font-frank-ruhl-libre",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${frankRuhlLibre.variable} antialiased`}
      >
        <AuthProvider>
          <Suspense fallback={<Spin />}>{children}</Suspense>
        </AuthProvider>
        <ToastContainer {...defaultToastContainerProps} />
      </body>
    </html>
  );
}
